<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="InvalidPipelineStoreException.xml" source-language="en-US" target-language="ko-KR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac59bbe4e4cfa38c1fd53c0b87c4aacce4d1e815312.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">9bbe4e4cfa38c1fd53c0b87c4aacce4d1e815312</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.AddIn.Hosting.InvalidPipelineStoreException">
          <source>The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.</source>
          <target state="translated">디렉터리가 없고 사용자에게 파이프라인 루트 경로 또는 추가 기능 경로에 액세스할 수 있는 권한이 없는 경우에 throw되는 예외입니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.AddIn.Hosting.InvalidPipelineStoreException">
          <source>Unlike <ph id="ph1">&lt;xref:System.IO.DirectoryNotFoundException&gt;</ph>, this exception does not provide any path information.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.IO.DirectoryNotFoundException&gt;</ph>과 달리 이 예외는 경로 정보를 제공하지 않습니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.AddIn.Hosting.InvalidPipelineStoreException">
          <source>This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.</source>
          <target state="translated">따라서 악의적인 사용자가 고의로 잘못된 경로를 지정하고 실제 경로를 확인하기 위해 예외를 통해 반환되는 정보를 사용하는 것을 막을 수 있습니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.AddIn.Hosting.InvalidPipelineStoreException">
          <source>This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <ph id="ph1">&lt;xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A&gt;</ph>,<ph id="ph2">&lt;xref:System.AddIn.Hosting.AddInStore.Rebuild%2A&gt;</ph>, <ph id="ph3">&lt;xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A&gt;</ph>, <ph id="ph4">&lt;xref:System.AddIn.Hosting.AddInStore.Update%2A&gt;</ph>, and <ph id="ph5">&lt;xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A&gt;</ph>.</source>
          <target state="translated">이 예외는 추가 기능 및 파이프라인 정보의 저장소를 업데이트 하는 검색 메서드에 의해 throw 됩니다: <ph id="ph1">&lt;xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A&gt;</ph>,<ph id="ph2">&lt;xref:System.AddIn.Hosting.AddInStore.Rebuild%2A&gt;</ph>, <ph id="ph3">&lt;xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A&gt;</ph>, <ph id="ph4">&lt;xref:System.AddIn.Hosting.AddInStore.Update%2A&gt;</ph>, 및 <ph id="ph5">&lt;xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A&gt;</ph>합니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" uid="T:System.AddIn.Hosting.InvalidPipelineStoreException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)">
          <source>A description of the error.</source>
          <target state="translated">오류에 대한 설명입니다.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> class with the specified message.</source>
          <target state="translated">지정된 메시지를 사용하여 <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The serialized object data.</source>
          <target state="translated">serialize된 개체 데이터입니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination object data.</source>
          <target state="translated">소스 또는 대상 개체 데이터에 대한 컨텍스트 정보입니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> class with serialization and streaming context information.</source>
          <target state="translated">serialization 및 스트리밍 컨텍스트 정보를 사용하여 <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream.</source>
          <target state="translated">이 생성자는 스트림을 통해 전송 되는 예외 개체를 다시 구성 하기 위해 역직렬화 하는 동안 호출 됩니다.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>.</source>
          <target state="translated">자세한 내용은 참조 <bpt id="p1">[</bpt>XML 및 SOAP Serialization<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>합니다.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>A description of the error.</source>
          <target state="translated">오류에 대한 설명입니다.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">현재 예외의 원인인 예외입니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.</source>
          <target state="translated"><bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> 매개 변수가 null 참조가 아닌 경우 내부 예외를 처리하는 catch 블록에서 현재 예외가 발생합니다.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> class with the specified message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">지정된 메시지와 해당 예외의 근본 원인인 내부 예외에 대한 참조를 사용하여 <ph id="ph1">&lt;see cref="T:System.AddIn.Hosting.InvalidPipelineStoreException" /&gt;</ph> 클래스의 새 인스턴스를 초기화합니다.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">이전 예외의 직접적인 결과로 throw되는 예외의 <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 속성에는 이전 예외에 대한 참조가 들어 있어야 합니다.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed to the constructor, or a null reference if the <ph id="ph2">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 경우 null 참조 또는 생성자에 전달 되는 동일한 값을 반환 하는 속성의 <ph id="ph2">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 속성이 생성자에 내부 예외 값을 제공 하지 않습니다.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>The following table shows the initial property values for an instance of the <ph id="ph1">&lt;xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException&gt;</ph> class.</source>
          <target state="translated">다음 표에서는 <ph id="ph1">&lt;xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException&gt;</ph> 클래스의 인스턴스에 대한 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>Property</source>
          <target state="translated">속성</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>Value</source>
          <target state="translated">값</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>The inner exception reference.</source>
          <target state="translated">내부 예외 참조</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)">
          <source>The localized error message string.</source>
          <target state="translated">지역화된 오류 메시지 문자열입니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>