<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="Rethrow.xml" source-language="en-US" target-language="ko-KR">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac56ec46005faec8045964b9fa5500e9be2216224b1.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">6ec46005faec8045964b9fa5500e9be2216224b1</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Activities.Statements.Rethrow">
          <source>Throws a previously thrown exception from within a <ph id="ph1">&lt;see cref="T:System.Activities.Statements.Catch" /&gt;</ph> activity.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Activities.Statements.Catch" /&gt;</ph> 작업 내에서 이전에 throw된 예외를 throw합니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.Statements.Rethrow">
          <source>The error is re-thrown retaining the original source of the exception.</source>
          <target state="translated">예외의 원래 소스를 보존하여 오류가 다시 throw됩니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Activities.Statements.Rethrow">
          <source><ph id="ph1">&lt;xref:System.Activities.Statements.Rethrow&gt;</ph> can only be used within a <ph id="ph2">&lt;xref:System.Activities.Statements.Catch&gt;</ph> block of a <ph id="ph3">&lt;xref:System.Activities.Statements.TryCatch&gt;</ph> activity.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Activities.Statements.Rethrow&gt;</ph>는 <ph id="ph2">&lt;xref:System.Activities.Statements.Catch&gt;</ph> 활동의 <ph id="ph3">&lt;xref:System.Activities.Statements.TryCatch&gt;</ph> 블록 내에서만 사용할 수 있습니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" uid="M:System.Activities.Statements.Rethrow.#ctor">
          <source>Creates a new instance of the <ph id="ph1">&lt;see cref="T:System.Activities.Statements.Rethrow" /&gt;</ph> activity.</source>
          <target state="translated"><ph id="ph1">&lt;see cref="T:System.Activities.Statements.Rethrow" /&gt;</ph> 활동의 새 인스턴스를 만듭니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>